version: '3'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDBPwd
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb_data:/data/db
    networks:
      - mongolibrary
  mongo-express:
    image: mongo-express
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: mongoep
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpressPwd
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDBPwd
    depends_on:
      - mongodb
    networks:
      - mongolibrary
      
networks: 
    mongolibrary:
      driver: bridge 
